# 2026 teaching team {.unnumbered}

# Instructor

**Prof. Alison Hill** ([alison.hill\@utoronto.ca](mailto:alison.hill@utoronto.ca))

Prof. Hill is a faculty member in the Department of Ecology & Evolutionary Biology. She runs a research group studying the dynamics and evolution of human infectious diseases within patients and across populations. Her team develops mathematical, statistical, and computational models to predict disease trajectories and help design interventions. Before moving to U of T, she was faculty at Johns Hopkins, and did her graduate and post-graduate training at Harvard. Coding is still her favourite part of her job, and she has used R - along with other programming languages - for many large open-source computational projects focusing on diseases such as COVID-19, HIV, RSV, and the opioid crisis.

## Teaching assistants

**Jessie Wang** ([jae.wang\@mail.utoronto.ca](mailto:jae.wang@mail.utoronto.ca))

Jessie is a 4th year PhD student in the Frederickson lab at UTSG. She studies plant-microbe interactions using high- throughput experimentation in duckweeds. She fell in love with R during her time as an undergraduate and took EEB313 in 2020, simultaneously sharpening her coding skills while conducting research alone in the lab. Jessie loves to spend too much money on fancy coffee as she types away, making sure her code is well-annotated and her figures look beautiful. Outside of work, she enjoys caring for her many houseplants and aquariums, finding new delicious eats, and admiring other people’s pets.

**Erik Curtis** ([erik.curtis\@mail.utoronto.ca](mailto:erik.curtis@mail.utoronto.ca)

Erik is a 2nd year PhD student interested in the epidemiology and population ecology of Pacific salmon, as well as the ecology of infectious diseases. In his PhD research, he is investigating the prevalence of co-infection in juvenile salmon. He's also using eDNA metabarcoding to examine the coastal marine community concurrent with juvenile salmon migration and salmon farm activity. Prior to joining the MK lab, he studied at the University of Notre Dame, majoring in Biology and Math, where he examined the fate and transport of eDNA in experimental streams. 

## Prior year course instructors

Mete Yuksel (Instructor Fall 2023 and Fall 2024)

Zoe Humphries (Instructor Fall 2024)

Vicki Zhang (Instructor Fall 2022 and Fall 2023)

James Santangelo (Fall 2018)

Ahmed Hasan (Fall 2018 and Fall 2019)

Amber Hoi

Luke Johnston (Fall 2017)

Madeleine Bonsma-Fisher (Fall 2017, 2018)

Lindsay Coome (Fall 2017, 2018)

Elliott Sales de Andrade (Fall 2017)

Sara Mahallati (Fall 2018)

Lina Tran (Fall 2017)

Joel Ostblom (Fall 2017. 2018)

## Other source material

\`**Data Analysis and Visualization in R for Ecologists**', Data Carpentry, https://datacarpentry.github.io/R-ecology-lesson/

Brian Seok, François Michonneau, Tobias Busch, Katrin Leinweber, Maneesha Sane, njlyon0, Ed Bennett, Hugo Tavares, Mike Mahoney, Paula Nieto, Susan Washko, Terry Loecke, Wasila Dahdul, xli677, Abhijna Parigi, Aleksander Jankowski, Allison Shay Theobold, Analytics Enlightened LLC, Anna K. Moeller, … vmzhang. (2024). '**datacarpentry/R-ecology-lesson: Data Carpentry: Data Analysis and Visualization in R for Ecologists 2024-07 (v2024.07)'**. Zenodo https://zenodo.org/records/12684301

Christie Bahlai, 'Reproducible Quantitative Methods', <https://cbahlai.github.io/rqm-template/>

<https://jose.theoj.org/papers/10.21105/jose.00049.pdf>
