# Assignment 01

1.  Vectors (2 marks)

    a.  Create a vector `v` with all integers 0-20, and a vector `w`
        with every third integer in the same range. (0.25 marks)

    b.  How much longer is vector `v` compared with `w`?
        (0.25 marks)
        
    c.  Create a new vector, `v_square`, with the square of elements at indices
        3, 6, 7, 10, and 15 from the variable `v`. _Hint:
        Use indexing rather than a for loop._ (0.5 marks)
        
    d.  Calculate the mean and median of the first four values from
        `v_square`. (0.5 marks)

    e.  Create a logical (or boolean) vector `v_bool` to indicate which vector `v_square`
        elements are bigger than 30. How many values are over 30? _Hint:
        In R, TRUE = 1, and FALSE = 0, so you can use simple arithmetic
        to find this out._ (0.5 marks)
        
2.  Functions (2 marks) 

Write a function that calculates the mean of the last two elements of any numeric vector. Test this function with the `v` and `v_square` vectors.
    
3.  Loops (2 marks)

Turn the given data frame into an exponent table, a table that shows you results of raising one number (the base, rows) to the power of another (the exponent, columns). See an example [here](https://djjr-courses.wdfiles.com/local--files/225:lab-discounting/power-table.gif). Use this data frame to find 5 to the power 9.
_Hint: use a [nested for-loop](https://rpubs.com/avbernat/596519) to fill your data frame_

>  `exp_table <- data.frame(matrix(ncol=10, nrow=10))`


4.  Data frames (2 marks)

    a.  There are many built-in data frames in R, which you can find
        [more details about these
        online](https://stat.ethz.ch/R-manual/R-devel/library/datasets/html/00Index.html).
        What are the column names of the built-in dataframe `beaver1`?
        How many observations (rows) and variables (columns) are there?
        (0.5 marks)

    b.  Display both the first 6 and last 6 rows of this data frame.
        Show how to do so with both indexing as well as specialized functions. (0.5 marks)

    c.  What is the difference in mean body temperature of the beaver when it was inside versus outside of the retreat? (0.5 marks)


    d.  How much did the body temperature of the beaver fluctuate (i.e., range) from 9:00-10:00 AM on the first day of the study? (0.5 marks)
    