# Open-access databases {-}

-----------------------------

Below are some resources that would be a good to look at if you are in search of data for the term project, or in search of a question in ecology or evolution:

- [GenBank](https://www.ncbi.nlm.nih.gov/genbank/): annotated collection of all publicly available DNA/protein sequences. It is possible to download sequences manually, but command line tools can help to automate the process.
- [PanTHERIA](https://esajournals.onlinelibrary.wiley.com/doi/10.1890/08-1494.1): database of ecology, life history, and geography of all extant and recently extinct mammal species. Includes body size, lifespan, litter size, and other trait data at the species level.
- [The Open Traits Network](https://opentraits.org/datasets.html) has information about trait datasets for other taxa -- including spiders, nematodes, amphibians, and birds!
- [Gene Expression Omnibus](https://www.ncbi.nlm.nih.gov/geo/): repository of gene expression, methylation, and annotated genomic data which are (like GenBank) most readily accessible using command line tools.
- [Continuous Plankton Recorder Survey](https://www.gbif.org/dataset/67c54f85-7910-4cbf-8de4-6f0b136a0e34): data (going back to 1958!) on northern hemisphere plankton species, including the location (latitude, longitude) and date of sampling.
- [Red-backed salamander abundance](https://open.canada.ca/data/en/dataset/3571474b-8d75-491d-816e-f84677b81a7c): abundance of red-backed salamanders from 4 sites in the Bruce Peninsula from 2004 to 2017.
- [North American Bird Breeding Survey](https://www.pwrc.usgs.gov/BBS/RawData/): repository containing information regarding the number of birds at multiple sites in North America. Many datasets of varying size that need to be linked together.
- [Malaria Atlas Project](https://malariaatlas.org): publicly available and up-to-date malaria prevalence and distribution data. Vector distribution, bednet coverage, etc. data also available.
- [GISAID](https://gisaid.org) hosts much of the available sequence data for rapidly-evolving RNA viruses such as influenza, SARS-CoV-2, monkeypox, and RSV as well as relevant meta-data (e.g., host species).
- [The Verena Institute](https://www.viralemergence.org/data) has developed a large collection of datasets on the interaction between pathogens, especially viruses, and their hosts. These datasets include information about surveillance/sampling, as well as more biological details.
 - [Dryad](https://datadryad.org/) is a searchable repository of publicaly-available datasets that have typically been released along with the publication of scientific paper
 - [PLOS Biology Recommended Repositories](https://journals.plos.org/plosbiology/s/recommended-repositories) has many great suggestions organized by subfield within biology