# Group project {.unnumbered}

## Project description

The course project is a self-directed group project where students can demonstrate their ability to use, adapt, and expand upon the computational skills gained in the course. Groups are free to do their projects on any topic within biology that they find exciting. There are two options for the form of the study:

1.  Analysis of a biological dataset, using visualization and statistical analysis
2.  Simulation of a biological process using a mathematical/computational model

Both approaches should be hypothesis-driven.

Since this is a class project, not a formal research project, we encourage you to **think outside the box, and be creative and ambitious**! You won't be accessed on the real life impact of your work, but on the use of skills learned in the class.

#### What is a hypothesis? What is a prediction?

A **hypothesis** is a testable and falsifiable statement that offers a possible explanation of a phenomenon based on background knowledge, preliminary observations, or logic.

*E.g., Primary productivity is an important driver of mammal species richness.*

A **prediction** is based on a hypothesis. It is meant to describe what will happen in a specific situation, such as during an experiment, if the hypothesis is correct.

*E.g., If primary productivity is an important driver of mammal species richness, then more mammalian species would be found in sites with more plant biomass (proxy for primary productivity) compared with sites with less plant growth.*

### Option 1: Data analysis

Groups will formulate their own hypotheses based on their interests within biology, and then use a (publicly-available) available dataset to test predictions borne out of their hypotheses with reproducible and quantitative analysis techniques. The analysis can use statistical/computational techniques that were covered in the class or ones you've learned elsewhere or independently. The work must be original; while you can repurpose data, you cannot simply redo the same analysis described in a published paper or other resource. The project should include, at minimum, data cleaning/pre-processing, visualization, description statistics, inferential statistics, and careful interpretation.

With this option, a good amount of time should be spent upfront finding the right match between a biologically-motivated hypothesis and an available dataset that could be used to test it.

Check out our continually-updated [list](projects_databases.html) of ideas for open-source datasets

### Option 2: Model simulation

Groups will develop a mathematical/computational model to answer a question in biology they find interesting. There are many reasons to develop models: they help clarify assumptions, generate predictions, nullify hypotheses, provide mechanistic explanations for observed data, and help us know *what kinds of data* to look for. New model are often build on existing and well-studied ones (e.g., the Lotka-Volterra model of species interactions, the SIR model of disease transmission, the Moran process for genetic drift and selection, Michaelis-Menton model of enzyme-substrate reactions, or reaction-diffusion model of developmental patterning). The fact models are simplifying representations of the real world is by design! The goal of building a model is to identify the key features that make a process interesting, represent the process mathematically (and, in doing so, clarify what assumptions are being made!), characterize the behaviour of the model, and from this characterization draw conclusions about how the process being modelled works. Characterization of a model can involve mathematical analysis, simulation, and confrontation with data.

The key steps in this project are to 1) identify an interesting question in biology, 2) develop (and likely revise) a simple model to address that question, 3) characterize the behaviour of the model, and 4) draw biological conclusions from the model and its characterization.

## Project timeline and deliverables

-   Project proposal (3 marks) - approx 1 page - due Thurs March 5th
-   Mid-project update (6 marks) - due Thurs March 19th
-   In-class Presentation (15 marks) - due Mar 30
-   Final report (15 marks) - due Apr 8

A single group document should be submitted for each project deliverable (NOT one per student).

Late submissions are not accepted for group project deadlines.

### Project proposal details

The project proposal should be 1 page max (plus citations, if appropriate), with formatting flexible (e.g., headings, bullet points, tables allowed). The proposal should cover the following three sections, with example content described below

-   [Research question]{.underline}: Describe the question, hypothesis, or goal you plan to address with your project. Give a little background and motivation for your choice of this question. Why do you think this is an interesting or important question? Were there any prior scientific studies that informed your choice of this question (not required, but if so, please cite)? Are there follow-up questions or alternative hypotheses that go along with your main question?

-   [Data source]{.underline}: Explain the dataset that you plan to analyze. How was this data collected? What is the unit being measured (ie, individuals, species, locations, etc)? What sorts of variables are recorded? How many observations are there? How are you accessing this data? What additional datasets could you use or seek out to supplement/validate your main analysis? Are there any major limitations of your data in relation to your research question? (Note: If you are doing a modeling project, this section can be shorter and might relate either to data you'll use to figure out input values for the parameters of your model, or data you will fit your model output to).

-   [Analysis plan]{.underline}: Outline what sorts of techniques you plan to use to analyze your data or simulate your model. Your analysis can include visualization and descriptive statistics but must go beyond that, to apply formal statistical inference (either something learned in class or a more advanced technique you teach yourself) or create a new model/simulation, or a combination of both.

The main goal of the proposal is mainly for the course instructors to ensure your team has a feasible analysis plan and reasonable scope, and for us to provide feedback on your idea as soon as possible.

### Mid-project update details

This update will have two components:

-   An individual component - a brief survey to be individually completed (1 pt)

-   A group component - described below, one submission per group (5 pts)

This progress report should be anywhere between 2-5 pages and should be created as an R markdown document and then submitted as a knitted PDF. The update should include the following sections and content

-   [Research question]{.underline}: Roughly, follow the same instructions above as for the original proposal, but update your text to reflect any changes you have made since then. Start with a short paragraph of background information on the topic, including important prior studies (include references), to motivate your approach. Then, describe the question, hypothesis, or goal you plan to address with your project. Are there follow-up questions or alternative hypotheses that go along with your main question?

-   [Data]{.underline}: Summarize in words the dataset that you plan to analyze. How was this data collected? What is the unit being measured (ie, individuals, species, locations, etc)? What sorts of variables are recorded? How many observations are there? How are you accessing this data? If you are using multiple datasets, describe each and then explain how they'll be linked. Are there any major limitations of your data in relation to your research question?

-   [Analysis]{.underline}:

    -   [Analysis Plan:]{.underline} Summarize in words what techniques you plan to use to address your research question. If there are a series of steps or multiple independent approaches, you can use a numbered or bulleted list to organize them. Make sure there is a clear and justified connection between your research questions and the approach you plan to use.

    -   [Preliminary results]{.underline}: Using a combination of text and well-annotated code, show some of your results to date. At minimum, this should include reading in and showing a sample of your data and then using some descriptive plots and summary statistics, as appropriate, to summarize your data. If you have begun any of your more formal analysis, you can show this here. Make sure to explain all your data manipulations, tables, and figures clearly and format them in a reader-friendly way.

### Final Report \[15 marks\]

The final report should be written in an `.Rmd` file where you include [headings]{.underline} to create sections (and subsections), [text]{.underline} to write the report text, [code chunks]{.underline} to write and run your code and generate your figures, and (if needed) the equation editing function (`Insert -> Latex Math`) to write equations.

The report should follow what you presented in class. We don't expect significant extra analysis, unless there was something specifically mentioned in your feedback or you identified an obvious and straighforward step that must be done to complete your original goal.

The report outline and constraints, which are similar in style to a scientific paper, are:

-   **Introduction** \[500 words max\]: Describe relevant prior background research or theoretical foundations informing your work, and your specific research question or hypothesis. Make sure you avoid using jargon and introduce all relevant concepts and terminology needed to explain your work. Don't assume anyone has any specific biological knowledge outside the class pre-reqs (ie BIO 220 and intro statistics/biostatistics). Include any images (not code-generated figures but pasted photos, diagrams, charts etc) that help explain the system you are working on, and your question.

-   **Methods** \[as needed but suggested 700 words max\]: Should include, at minimum, to subsections - *Data*, and *Analysis*. For the *Data* subsection, follow the same instructions provided for the interim reports, and a similar approach to used in the presentation, to describe your dataset. For the *Analysis* subsection, describe in a systematic way the specific methods that you use to analyze your data. If you tried out a method and didn't end up using the results from it you don't need to mention it here. Any statistical/regression models you fit should be stated here. State which R packages you used for specific model fits (and if it's a new package we didn't use in class, summarize what it does). Note that this section should not yet contain any code or results. If you need an image to help explain your data or your methods, you can include that, but you don't need any data-generated output.

-   **Results** \[as needed but suggested 1000 words max\]: This can be divided up into subsections of your choosing. It should be a mix of text and code, similar to our assignments. Summarize in words what you did and what you found, then include the code and figure/table output that shows the results. Try to make things as compact as possible - write your code efficiently, output your figures at a reasonable size, and only output things you really need to show, etc. Don't show output that you wouldn't have shown in your presentation. Don't include code that is not necessary for your main analysis and results (if you don't want to delete things, move them to a separate "code dump" file that you don't submit). Don't force the reader to search through code or code output for an important result ... summarize it in the text. The code/output is just to backup and reproduce your point, not to make the point. Make sure your figures are labeled and everything is legible. Make sure to walk the reader through WHY you are doing an analysis, what the results of the analysis are, and what the interpretation is.

-   **Discussion** \[500 words max\]: Summarize your findings, interpreted in the context of your original question. If appropriate, put your work in the context of prior related research. Discuss any limitations to your data or analysis. Suggest future work (in terms of data collection, other analysis, or related questions). End with a conclusion. Don't include any new results in this section. You don't need any figures here unless they provide a summary of previously discussed results.

Note that word counts are *maximum*, not targets. If you can say what you need to say in significantly less words that the max, please do so!

## Miscellaneous

### Working in groups

All group members are expected to contribute equally to the conception and execution of the project. Each group member must be present for each class session (barring illness/emergency), available to convene outside of class, and responsive to communication with group members between meetings in a timely manner.

If you are having trouble working with your group, e.g., because you feel like the work is not being equitably divided, please let us know as soon as possible. We will work with you and your group to identify a solution that works for everyone. Do not wait until the last minute to let us know that your group has been having trouble -- at that point, there is little we can do to fix the situation. Moreover, we expect group members to communicate with each other and to try to work out their concerns before we become involved.

If an individual is unable to effectively work with a group, they will be removed and asked to complete the project alone.
