---
title: 'Individual Interest description'
output:
  pdf_document: default
---

*To submit this assignment, upload the full document on Quercus, including the original questions, your code, and the output. Submit your assignment as a knitted `.pdf`.*

\vspace{12pt}

1. Get set up at home (or on a lab computer after hours)
    -   If you have not already done so, install [R](https://cran.rstudio.com/) and [RStudio](https://www.rstudio.com/products/rstudio/download/) (already installed on the lab computers).
    -   Open a new R Notebook and read the instructions about how to use the R Markdown syntax.
    -   Open this assignment file in RStudio or copy its content into an empty R Notebook.
    -   Insert a code chunk below, above Question 2. Set `eval=FALSE`
    -   In the code chunk, use `install.packages("<package_name>")` to install `tidyverse` and `rmarkdown`. Remember to run the code chunk to execute the commands.
    -   Load the two libraries you just installed into your environment with `library(<package_name>)` (no surrounding quotation marks). Add this to the same code chunk you created previously and execute it again.
        - Don't worry that the `install.packages()` commands have already been executed once, R is smart and checks if you already have those installed.
    -   Run `sessionInfo()` to list all the loaded packages.
        -   You should see the following packages under "other attached packages": `rmarkdown`, `dplyr`, `purrr`, `readr`, `tidyr`, `tibble`, `ggplot`, and `tidyverse`.
    -   Since this is your first assignment, we have already completed most of this question below. You still need to run the code chunk on your computer to confirm that the packages installed and to get the `sessionInfo()` output for your computer. You might receive warnings that functions from other packages are masked when you load `tidyverse`, but this is fine.
    
\vspace{12pt}

2. In 4-5 sentences, what are some of the topics/questions in ecology and evolutionary biology you are interested in for the group project?
